### ISSUE TITLE
Dry run fails when apptainer-compatible docker image is not already downloaded.

### ISSUE THREAD

**Issue by cmkobel** [cmkobel/assemblycomparator2#60]
On a fresh install, when issuing "asscom2 --dry-run" snakemake throws a fatal error because the docker image is not present. This is of cause a false error, as the dry run should not expect this image to necessarily be downloaded and ready yet.

```
Building DAG of jobs...                                                                                                                                                       
Singularity image docker://cmkobel/assemblycomparator2:v2.5.5 will be pulled.                                                                                                 
FATAL:   While checking container encryption: could not open image /glittertind/home/memouser/.asscom2/singularity-prefix/a59aab1798232d02c16749f5d9cc1ef7.simg: failed to ret
rieve path for /glittertind/home/memouser/.asscom2/singularity-prefix/a59aab1798232d02c16749f5d9cc1ef7.simg: lstat /glittertind/home/memouser/.asscom2/singularity-prefix/a59a
ab1798232d02c16749f5d9cc1ef7.simg: no such file or directory                                                                                                                  
Traceback (most recent call last):                                                                                                                                            
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/__init__.py", line 792, in snakemake                                             
    success = workflow.execute(                                                                                                                                               
              ^^^^^^^^^^^^^^^^^                                                                                                                                               
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/workflow.py", line 1078, in execute                                              
    dag.create_conda_envs(                                                                                                                                                    
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/dag.py", line 358, in create_conda_envs                                          
    env.create(dryrun)                                                                                                                                                        
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/deployment/conda.py", line 393, in create                                        
    pin_file = self.pin_file                                                                                                                                                  
               ^^^^^^^^^^^^^                                                                                                                                                  
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/common/__init__.py", line 217, in __get__                                        
    value = self.method(instance)                                                                                                                                             
            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                             
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/deployment/conda.py", line 103, in pin_file                                      
    f".{self.conda.platform}.pin.txt"                                                                                                                                         
        ^^^^^^^^^^                                                                                                                                                            
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/common/__init__.py", line 217, in __get__                                        
    value = self.method(instance)                                                                                                                                             
            ^^^^^^^^^^^^^^^^^^^^^                                                                                                                                             
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/deployment/conda.py", line 96, in conda                                          
    return Conda(                                                                                                                                                             
           ^^^^^^                                                                                                                                                             
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/deployment/conda.py", line 653, in __init__                                      
    shell.check_output(self._get_cmd("conda info --json"), text=True)                                                                                                         
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/site-packages/snakemake/shell.py", line 61, in check_output                                              
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)                                                                                                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                  
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/subprocess.py", line 466, in check_output                                                                
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          
  File "/glittertind/home/memouser/conda_envs/asscom2/lib/python3.11/subprocess.py", line 571, in run                                                                         
    raise CalledProcessError(retcode, process.args,                                                                                                                           
subprocess.CalledProcessError: Command ' singularity --quiet --silent exec --home '/glittertind/home/memouser/test_ac2_install'  /glittertind/home/memouser/.asscom2/singulari
ty-prefix/a59aab1798232d02c16749f5d9cc1ef7.simg sh -c 'conda info --json'' returned non-zero exit status 255.           
```

**Comment by cmkobel** [comment]
The solution is to not run a "dry run" (`asscom2 --dry-run`) on a fresh installation when the apptainer compatible docker image has not yet been downloaded. Instead, run `asscom2 --until fast` to check that _things are working_.

**Comment by cmkobel** [comment]
Updated the documentation to avoid that new users might run into this problem.
https://github.com/cmkobel/assemblycomparator2/commit/013246e649ec8ede213e4c59b81bef18744b0a4c

**Comment by cmkobel** [comment]
This seems to be the same issue.
https://github.com/snakemake/snakemake/issues/1901
